### ISSUE TITLE
Regenerate container image in order to fix rpminspect issue with false positive in go binaries in Rawhide

### ISSUE THREAD

**Issue by carlosrodfern** [fedora-ci/rpminspect-runner#127]
Could we please have the rpminspect image regenerated to pick up the latest version of annobin?

The current version is causing issues with false positives in go binaries. Please see the following issue for more information: https://bugzilla.redhat.com/show_bug.cgi?id=2292658

Thank you!

**Comment by msrb** [comment]
Image updated ;) It runs annocheck 12.59 now.
