### ISSUE TITLE
Regenerate container image in order to fix rpminspect issue with false stack realignment positive for LTO mode in Rawhide

### ISSUE THREAD

**Issue by carlosrodfern** [fedora-ci/rpminspect-runner#129]
Could we please have the rpminspect image regenerated to pick up the latest 12.66 version of annobin?

The current version is causing issues with false stack realignment positives . Please see the following issue for more information: https://bugzilla.redhat.com/show_bug.cgi?id=2302427

12.66 is not available yet as of the creation of this ticket: https://bodhi.fedoraproject.org/updates/FEDORA-2024-3598ea9717

Thank you!

**Comment by thrix** [comment]
I can try to do it
